# nixpacks.toml

[phases.setup]
nixPkgs = ["python39", "ffmpeg", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python bot.py" 
